name: Build and Release

on: [push, pull_request]

concurrency:
  group: ci-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'push' }}

env:
  BUILD_TYPE: Release

jobs:
  reuse:
    runs-on: ubuntu-24.04
    continue-on-error: true
    steps:
    - uses: actions/checkout@v5
    - uses: fsfe/reuse-action@v5

  clang-format:
    runs-on: ubuntu-24.04
    continue-on-error: true
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Install
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository 'deb http://apt.llvm.org/noble/ llvm-toolchain-noble-19 main'
        sudo apt update
        sudo apt install clang-format-19
    - name: Build
      env:
        COMMIT_RANGE: ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
      run: ./.ci/clang-format.sh

  get-info:
    runs-on: ubuntu-24.04
    outputs:
      date: ${{ steps.vars.outputs.date }}
      shorthash: ${{ steps.vars.outputs.shorthash }}
      fullhash: ${{ steps.vars.outputs.fullhash }}
    steps:
    - uses: actions/checkout@v5
    - name: Get date and git hash
      id: vars
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        echo "shorthash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "fullhash=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        echo "shorthash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "fullhash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  # ---------------- WINDOWS ----------------
  windows-sdl:
    runs-on: windows-2025
    needs: get-info
    steps:
    - uses: actions/checkout@v5

    # Grab all externals into externals/* so CMake finds them. [web:27][web:102]
    - name: Fetch externals
      uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-boost
        path: externals/ext-boost
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-fmt
        path: externals/fmt
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-ffmpeg-core
        path: externals/ffmpeg-core
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-zlib-ng
        path: externals/zlib-ng
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-glslang
        path: externals/glslang
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-half
        path: externals/half
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-magic_enum
        path: externals/magic_enum
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-sdl3
        path: externals/sdl3
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-sdl3_mixer
        path: externals/sdl3_mixer
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-stb
        path: externals/stb
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-toml11
        path: externals/toml11
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-tsl-robin-map
        path: externals/tsl-robin-map
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-vulkan-headers
        path: externals/Vulkan-Headers
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-vma
        path: externals/VulkanMemoryAllocator
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-xbyak
        path: externals/xbyak
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-xxHash
        path: externals/xxHash
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-zydis
        path: externals/Zydis
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-pugixml
        path: externals/pugixml

    - name: Cache CMake Configuration
      uses: actions/cache@v4
      env:
          cache-name: ${{ runner.os }}-sdl-ninja-cache-cmake-configuration
      with:
          path: | 
            ${{github.workspace}}/build
          key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', 'cmake/**', 'externals/**') }}
          restore-keys: |
            ${{ env.cache-name }}-

    - name: Cache CMake Build
      uses: hendrikmuhs/ccache-action@v1.2.19
      env:
          cache-name: ${{ runner.os }}-sdl-cache-cmake-build
      with:
        append-timestamp: false
        key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', 'cmake/**', 'externals/**') }}

    - name: Configure CMake
      run: cmake --fresh -G Ninja -B ${{github.workspace}}/build ^
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ^
        -DCMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE=ON ^
        -DCMAKE_C_COMPILER=clang-cl ^
        -DCMAKE_CXX_COMPILER=clang-cl ^
        -DCMAKE_C_COMPILER_LAUNCHER=ccache ^
        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel $env:NUMBER_OF_PROCESSORS

    - name: Upload Windows SDL artifact
      uses: actions/upload-artifact@v4
      with:
        name: shadps4-win64-sdl-${{ needs.get-info.outputs.date }}-${{ needs.get-info.outputs.shorthash }}
        path: ${{github.workspace}}/build/shadPS4.exe

  # ---------------- MACOS ----------------
  macos-sdl:
    runs-on: macos-15
    needs: get-info
    steps:
    - uses: actions/checkout@v5

    - name: Fetch externals
      uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-boost
        path: externals/ext-boost
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-fmt
        path: externals/fmt
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-ffmpeg-core
        path: externals/ffmpeg-core
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-zlib-ng
        path: externals/zlib-ng
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-glslang
        path: externals/glslang
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-half
        path: externals/half
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-magic_enum
        path: externals/magic_enum
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-sdl3
        path: externals/sdl3
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-sdl3_mixer
        path: externals/sdl3_mixer
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-stb
        path: externals/stb
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-toml11
        path: externals/toml11
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-tsl-robin-map
        path: externals/tsl-robin-map
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-vulkan-headers
        path: externals/Vulkan-Headers
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-vma
        path: externals/VulkanMemoryAllocator
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-xbyak
        path: externals/xbyak
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-xxHash
        path: externals/xxHash
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-zydis
        path: externals/Zydis
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-pugixml
        path: externals/pugixml

    - name: Setup latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - name: Cache CMake Configuration
      uses: actions/cache@v4 
      env: 
          cache-name: ${{ runner.os }}-sdl-cache-cmake-configuration
      with: 
          path: |  
            ${{github.workspace}}/build 
          key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', 'cmake/**', 'externals/**') }} 
          restore-keys: |
            ${{ env.cache-name }}- 

    - name: Cache CMake Build
      uses: hendrikmuhs/ccache-action@v1.2.19
      env:
          cache-name: ${{runner.os}}-sdl-cache-cmake-build
      with:
        append-timestamp: false
        create-symlink: true
        key: ${{env.cache-name}}-${{ hashFiles('**/CMakeLists.txt', 'cmake/**', 'externals/**') }}
        variant: sccache

    - name: Configure CMake
      run: cmake --fresh -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE=ON -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel $(sysctl -n hw.ncpu)

    - name: Package and Upload macOS SDL artifact
      run: |
        mkdir upload
        mv ${{github.workspace}}/build/shadps4 upload
        mv ${{github.workspace}}/build/MoltenVK_icd.json upload
        mv ${{github.workspace}}/build/libMoltenVK.dylib upload
    - uses: actions/upload-artifact@v4
      with:
        name: shadps4-macos-sdl-${{ needs.get-info.outputs.date }}-${{ needs.get-info.outputs.shorthash }}
        path: upload/

  # ---------------- LINUX (clang) ----------------
  linux-sdl:
    runs-on: ubuntu-24.04
    needs: get-info
    steps:
    - uses: actions/checkout@v5

    - name: Fetch externals
      uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-boost
        path: externals/ext-boost
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-fmt
        path: externals/fmt
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-ffmpeg-core
        path: externals/ffmpeg-core
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-zlib-ng
        path: externals/zlib-ng
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-glslang
        path: externals/glslang
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-half
        path: externals/half
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-magic_enum
        path: externals/magic_enum
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-sdl3
        path: externals/sdl3
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-sdl3_mixer
        path: externals/sdl3_mixer
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-stb
        path: externals/stb
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-toml11
        path: externals/toml11
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-tsl-robin-map
        path: externals/tsl-robin-map
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-vulkan-headers
        path: externals/Vulkan-Headers
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-vma
        path: externals/VulkanMemoryAllocator
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-xbyak
        path: externals/xbyak
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-xxHash
        path: externals/xxHash
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-zydis
        path: externals/Zydis
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-pugixml
        path: externals/pugixml

    - name: Add LLVM repository
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository 'deb http://apt.llvm.org/noble/ llvm-toolchain-noble-19 main'

    - name: Install dependencies
      run: sudo apt-get update && sudo apt install -y libx11-dev libxext-dev libwayland-dev libdecor-0-dev libxkbcommon-dev libglfw3-dev libgles2-mesa-dev libfuse2 clang-19 mold build-essential libasound2-dev libpulse-dev libopenal-dev libudev-dev libxcursor-dev libxi-dev libxss-dev libxtst-dev

    - name: Cache CMake Configuration
      uses: actions/cache@v4 
      env: 
          cache-name: ${{ runner.os }}-sdl-cache-cmake-configuration
      with: 
          path: |  
            ${{github.workspace}}/build 
          key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', 'cmake/**', 'externals/**') }} 
          restore-keys: |
            ${{ env.cache-name }}- 

    - name: Cache CMake Build
      uses: hendrikmuhs/ccache-action@v1.2.19
      env:
          cache-name: ${{ runner.os }}-sdl-cache-cmake-build
      with:
        append-timestamp: false
        key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', 'cmake/**', 'externals/**') }}

    - name: Configure CMake
      run: cmake --fresh -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE=ON -DCMAKE_C_COMPILER=clang-19 -DCMAKE_CXX_COMPILER=clang++-19 -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold" -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=mold" -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel $(nproc)
  
    - name: Package and Upload Linux(ubuntu64) SDL artifact 
      run: |
        ls -la ${{ github.workspace }}/build/shadps4
    
    - uses: actions/upload-artifact@v4
      with:
        name: shadps4-ubuntu64-${{ needs.get-info.outputs.date }}-${{ needs.get-info.outputs.shorthash }}
        path: ${{ github.workspace }}/build/shadps4

    - name: Run AppImage packaging script
      run:  ./.github/linux-appimage-sdl.sh
      
    - name: Package and Upload Linux SDL artifact
      run: |
        tar cf shadps4-linux-sdl.tar.gz -C ${{github.workspace}}/build shadps4
    - uses: actions/upload-artifact@v4
      with:
        name: shadps4-linux-sdl-${{ needs.get-info.outputs.date }}-${{ needs.get-info.outputs.shorthash }}
        path: Shadps4-sdl.AppImage

  # ---------------- LINUX (gcc) ----------------
  linux-sdl-gcc:
    runs-on: ubuntu-24.04
    needs: get-info
    steps:
    - uses: actions/checkout@v5

    - name: Fetch externals
      uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-boost
        path: externals/ext-boost
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-fmt
        path: externals/fmt
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-ffmpeg-core
        path: externals/ffmpeg-core
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-zlib-ng
        path: externals/zlib-ng
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-glslang
        path: externals/glslang
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-half
        path: externals/half
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-magic_enum
        path: externals/magic_enum
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-sdl3
        path: externals/sdl3
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-sdl3_mixer
        path: externals/sdl3_mixer
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-stb
        path: externals/stb
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-toml11
        path: externals/toml11
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-tsl-robin-map
        path: externals/tsl-robin-map
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-vulkan-headers
        path: externals/Vulkan-Headers
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-vma
        path: externals/VulkanMemoryAllocator
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-xbyak
        path: externals/xbyak
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-xxHash
        path: externals/xxHash
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-zydis
        path: externals/Zydis
    - uses: actions/checkout@v5
      with:
        repository: shadps4-emu/ext-pugixml
        path: externals/pugixml

    - name: Install dependencies
      run: sudo apt-get update && sudo apt install -y libx11-dev libxext-dev libwayland-dev libdecor-0-dev libxkbcommon-dev libglfw3-dev libgles2-mesa-dev libfuse2 gcc-14 mold build-essential libasound2-dev libpulse-dev libopenal-dev libudev-dev libxcursor-dev libxi-dev libxss-dev libxtst-dev

    - name: Cache CMake Configuration
      uses: actions/cache@v4 
      env: 
          cache-name: ${{ runner.os }}-sdl-gcc-cache-cmake-configuration
      with: 
          path: |  
            ${{github.workspace}}/build 
          key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', 'cmake/**', 'externals/**') }} 
          restore-keys: |
            ${{ env.cache-name }}- 

    - name: Cache CMake Build
      uses: hendrikmuhs/ccache-action@v1.2.19
      env:
          cache-name: ${{ runner.os }}-sdl-gcc-cache-cmake-build
      with:
        append-timestamp: false
        key: ${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt', 'cmake/**', 'externals/**') }}

    - name: Configure CMake
      run: cmake --fresh -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE=ON -DCMAKE_C_COMPILER=gcc-14 -DCMAKE_CXX_COMPILER=g++-14 -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold" -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=mold" -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel $(nproc)

  # pre-release job left exactly as in your original
  pre-release:
    if: github.ref == 'refs/heads/main' && github.repository == 'shadps4-emu/shadPS4' && github.event_name == 'push'
    needs: [get-info, windows-sdl, macos-sdl, linux-sdl]
    runs-on: ubuntu-latest
    steps:
      # ... keep your original pre-release steps here ...
